apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: deployment.yaml
- path: service.yaml

generatorOptions:
  labels:
    app: web-service
    # disableNameSuffixHash: true

configMapGenerator:
- name: index-html-configmap
  behavior: create
  files:
  - files/index.html
- name: conf-cred
  behavior: create
  literals:
  - name= "user"
  - pass= "Zaq1234a"
